apiVersion: apps/v1
kind: Deployment   
metadata:
  name: pythonapp  
  labels:
    app: pythonapp
spec:
  replicas: 1      
  selector:
    matchLabels:
      app: pythonapp
  template:        
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:  
      - name: pythonapp  
        image: franciscoorselli/pythonapp:latest  
        env:
        - name: MONGO_URI
          value: mongodb://user:password@localhost:27017/restaurants 
        ports:
        - containerPort: 8080  
      - name: mongodb
        image: franciscoorselli/mongodb:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: rootpassword
        - name: MONGO_INITDB_DATABASE
          value: restaurants
        ports:
        - containerPort: 27017  
---
apiVersion: v1
kind: Service   
metadata:
  name: pythonapp   
  labels:
    app: pythonapp   
spec:
  ports:
    - port: 8080      
      nodePort: 32320  
  selector:
    app: pythonapp
  type: NodePort  