on: push
name: deploy
jobs:
  deploy:
    name: Test and deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Tox and any other packages
      run: pip install tox
    - name: Run Tox
      run: tox -e py
    - name: pythonapp build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: franciscoorselli/pythonapp
        dockerfile: Dockerfile.pythonapp
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
    - name: mongodb build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: franciscoorselli/mongodb
        dockerfile: Dockerfile.mongodb
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.0.0
      with:
        minikube version: 'v1.9.2'
        kubernetes version: 'v1.18.2'
    - name: Deploy app
      run: kubectl create -f kubernetes-deployment.yaml
    - name: Wait app to be deployed
      run: sleep 120
    - name: Check cluster status
      run: kubectl get all
    - name: curl
      uses: wei/curl@master
      with:
        args: localhost:32320/api/v1/restaurant
